name: PR Verify

permissions:
  contents: read

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Display Go version
        run: go version

      - name: Build application
        run: go build

      - name: Test application
        run: go test ./...

      - name: Format application
        # $() captures the output from the go fmt command and places it into the outer command
        # test -z checks if the output is empty, returning 0 if it is and 1 if it isn't
        run: test -z $(go fmt ./...)

      # LINTING
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Lint application
        run: staticcheck ./...

      # SECURE CODE ANALYSIS
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec ./...
